# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.hostname = "arnaud-vm"
  config.vm.network "private_network", ip: "192.168.5.2"
  config.vm.define "arnaud-wm"
  config.vm.synced_folder "./data", "/vagrant_data"


  config.vm.provider "virtualbox" do |vb|
    vb.name = "arnaud-wm"
    vb.gui = false
    vb.memory = "3072"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]    
  end

  config.vm.provision "shell", run: "always", inline: <<-SHELL
    echo "HELLO from Vagrantfile"
  SHELL

  config.vm.provision "shell", path: "install_pelican.sh"

  config.vm.provision "shell", path: "install_gitlab.sh"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "install_docker.yaml"
  end

end
